# Manipulación de Arrays en NumPy 1
Crea dos arrays unidimensionales, `array1` y `array2`, donde array1 contiene los números del 1 al 5 y array2 contiene los números del 6 al 10. Utiliza la función de numpy adecuada para concatenar array1 y array2 en un nuevo array llamado `array_concatenado`.

In [1]:
import numpy as np
array1 = np.array([1,2,3,4,5])
array2 = np.array([6,7,8,9,10])
array_concatenado = np.concat([array1,array2])
array_concatenado

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Manipulación de Arrays en NumPy 2
Crea un array unidimensional array_original con los números del 1 al 6, utiliza el método correcto para transformarlo en un array bidimensional de 2 filas y 3 columnas. Almacena el resultado en una variable llamada array_reshaped

In [2]:
import numpy as np
array_original = np.array([1,2,3,4,5,6]) 
array_reshaped = array_original.reshape(2,3)
array_reshaped

array([[1, 2, 3],
       [4, 5, 6]])

# Manipulación de Arrays en NumPy 3
Crea un array bidimensional A de forma 2x2 que contenga los números del 1 al 4.

Crea otro array bidimensional B de la misma forma que contenga los números del 5 al 8.

Realiza las siguientes operaciones e imprime los resultados:

1. La suma de A y B. Almacena el resultado en una variable llamada suma_AB
2. El producto elemento a elemento de A y B. Almacena el resultado en una variable llamada productoAB

In [7]:
import numpy as np

A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

suma_AB = A + B
suma_AB

productoAB = A * B
productoAB

array([[ 5, 12],
       [21, 32]])