In [1]:
import numpy as np

array1d = np.array([1,2,3,4,5])
array1d[0]

np.int64(1)

In [4]:
array2d = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
array2d[0][1]

np.int64(2)

In [5]:
array1d[1:3]

array([2, 3])

In [6]:
array2d[1,:]

array([ 6,  7,  8,  9, 10])

In [7]:
array2d[1,:3]

array([6, 7, 8])

In [8]:
array2d[:, 1]

array([ 2,  7, 12])

In [9]:
array2d[:2, :2]

array([[1, 2],
       [6, 7]])

In [10]:
array1d > 3

array([False, False, False,  True,  True])

In [11]:
array2d % 2 == 0

array([[False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False]])