In [3]:
import numpy as np
array = np.arange(1,10)
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
array_mod = array.reshape(-1, 3)
array_mod

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
array_voltado = array_mod.transpose()
array_voltado

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [7]:
# create a copy
array_flat = array.flatten()
array_flat

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
# generate a view of the array, less memory
array_flat = array.ravel()
array_flat

array([1, 2, 3, 4, 5, 6, 7, 8, 9])