In [1]:
import numpy as np
array1 = np.array([1,2,3])
array1

array([1, 2, 3])

In [4]:
array2 = np.array([[0],[10],[20],[30]])
array2

array([[ 0],
       [10],
       [20],
       [30]])

In [6]:
broadcast = array2 + array1
broadcast

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [7]:
multi = array2 *array1
multi

array([[ 0,  0,  0],
       [10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

In [8]:
a = np.arange(1,4)
b = np.arange(4,7)
resultado = np.add(a,b)
resultado
# substract, multiy, divide

array([5, 7, 9])

In [9]:
result_2 = np.exp(a)
result_2

array([ 2.71828183,  7.3890561 , 20.08553692])