# Operaciones Avanzadas y Funciones Universales en NumPy 1
Crea un programa que defina dos arrays usando NumPy: el primer array `A` debe ser un array unidimensional de 5 elementos, iniciando en 1 y con pasos de 2 (i.e., [1, 3, 5, 7, 9]), y el segundo array `B` debe ser un array bidimensional de forma (5,1), con valores que comiencen en 10 y aumenten de 10 en 10 (i.e., [[10], [20], [30], [40], [50]]).

Utiliza el concepto de broadcasting para sumar estos dos arrays y almacena su resultado en una variable llamada `resultado`

In [8]:
import numpy as np

A = np.arange(1, 10, 2)
print(A)
B = np.arange(10, 51, 10).reshape(5,1)
print(B)
resultado = A + B
resultado

[1 3 5 7 9]
[[10]
 [20]
 [30]
 [40]
 [50]]


array([[11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49],
       [51, 53, 55, 57, 59]])

# Operaciones Avanzadas y Funciones Universales en NumPy 2
Crea un programa que defina dos arrays usando NumPy: el primer array `A` debe ser un array unidimensional de 10 elementos, iniciando en 1 hasta el 10, y el segundo array `B` debe ser un array bidimensional de forma (5,1), con valores que comiencen en 10 y aumenten de 10 en 10 (i.e., [[10], [20], [30], [40], [50]]).

Utiliza el concepto de broadcasting para multiplicar estos dos arrays almacena el resultado en una variable llamada `resultado`

In [12]:
import numpy as np
A = np.arange(1, 11)
B = np.arange(10, 51, 10).reshape(5,1)
resultado = A * B
resultado

array([[ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100],
       [ 20,  40,  60,  80, 100, 120, 140, 160, 180, 200],
       [ 30,  60,  90, 120, 150, 180, 210, 240, 270, 300],
       [ 40,  80, 120, 160, 200, 240, 280, 320, 360, 400],
       [ 50, 100, 150, 200, 250, 300, 350, 400, 450, 500]])

# Operaciones Avanzadas y Funciones Universales en NumPy 3
Crea un programa que defina un array usando NumPy: `A` debe ser un array unidimensional de solamente 3 elementos, iniciando en 1 y terminando en 3 (inclusive)

Utiliza la función matemática adecuada para almacenar en una variable llamada `resultado` el exponente de cada numero contenido en A

In [13]:
import numpy as np
A = np.arange(1,4)
resultado = np.exp(A)
resultado

array([ 2.71828183,  7.3890561 , 20.08553692])