In [1]:
import numpy as np

medallas_csv_url = "./medallas.csv"
array = np.genfromtxt(medallas_csv_url)
array

ValueError: Some errors were detected !
    Line #15 (got 2 columns instead of 1)
    Line #17 (got 2 columns instead of 1)
    Line #20 (got 2 columns instead of 1)
    Line #22 (got 2 columns instead of 1)
    Line #24 (got 2 columns instead of 1)
    Line #27 (got 4 columns instead of 1)
    Line #36 (got 2 columns instead of 1)
    Line #39 (got 3 columns instead of 1)
    Line #44 (got 4 columns instead of 1)
    Line #63 (got 2 columns instead of 1)
    Line #65 (got 2 columns instead of 1)
    Line #70 (got 2 columns instead of 1)
    Line #72 (got 3 columns instead of 1)
    Line #73 (got 3 columns instead of 1)
    Line #74 (got 4 columns instead of 1)
    Line #77 (got 2 columns instead of 1)
    Line #78 (got 2 columns instead of 1)
    Line #82 (got 2 columns instead of 1)
    Line #86 (got 3 columns instead of 1)

In [3]:
import numpy as np

medallas_csv_url = "./medallas.csv"
array = np.genfromtxt(medallas_csv_url,delimiter=',', filling_values=0)
array

array([[  0.,   0.,   0.,   0.,   0.],
       [  0.,   1.,   2.,   3.,   0.],
       [  0.,   2.,   2.,   4.,   0.],
       [ 17.,   7.,  22.,  46.,   0.],
       [  1.,   1.,   5.,   7.,   0.],
       [  0.,   3.,   4.,   7.,   0.],
       [  2.,   0.,   0.,   2.,   0.],
       [  0.,   1.,   0.,   1.,   0.],
       [  1.,   3.,   3.,   7.,   0.],
       [  3.,   1.,   3.,   7.,   0.],
       [  1.,   0.,   0.,   1.,   0.],
       [  0.,   0.,   1.,   1.,   0.],
       [  7.,   6.,   8.,  21.,   0.],
       [  3.,   1.,   2.,   6.,   0.],
       [  0.,   0.,   1.,   1.,   0.],
       [  7.,   6.,  11.,  24.,   0.],
       [  2.,   4.,   6.,  12.,   0.],
       [  0.,   4.,   1.,   5.,   0.],
       [  3.,   3.,   2.,   8.,   0.],
       [  0.,   0.,   1.,   1.,   0.],
       [  7.,   3.,   5.,  15.,   0.],
       [  4.,   4.,   3.,  11.,   0.],
       [  3.,   4.,   4.,  11.,   0.],
       [  0.,   3.,   2.,   5.,   0.],
       [  2.,   1.,   0.,   3.,   0.],
       [  1.,   1.,   4.,

In [4]:
import numpy as np

medallas_csv_url = "./medallas.csv"
# remove the header
array = np.genfromtxt(medallas_csv_url,delimiter=',', filling_values=0,skip_header=1)
array

array([[  0.,   1.,   2.,   3.,   0.],
       [  0.,   2.,   2.,   4.,   0.],
       [ 17.,   7.,  22.,  46.,   0.],
       [  1.,   1.,   5.,   7.,   0.],
       [  0.,   3.,   4.,   7.,   0.],
       [  2.,   0.,   0.,   2.,   0.],
       [  0.,   1.,   0.,   1.,   0.],
       [  1.,   3.,   3.,   7.,   0.],
       [  3.,   1.,   3.,   7.,   0.],
       [  1.,   0.,   0.,   1.,   0.],
       [  0.,   0.,   1.,   1.,   0.],
       [  7.,   6.,   8.,  21.,   0.],
       [  3.,   1.,   2.,   6.,   0.],
       [  0.,   0.,   1.,   1.,   0.],
       [  7.,   6.,  11.,  24.,   0.],
       [  2.,   4.,   6.,  12.,   0.],
       [  0.,   4.,   1.,   5.,   0.],
       [  3.,   3.,   2.,   8.,   0.],
       [  0.,   0.,   1.,   1.,   0.],
       [  7.,   3.,   5.,  15.,   0.],
       [  4.,   4.,   3.,  11.,   0.],
       [  3.,   4.,   4.,  11.,   0.],
       [  0.,   3.,   2.,   5.,   0.],
       [  2.,   1.,   0.,   3.,   0.],
       [  1.,   1.,   4.,   6.,   0.],
       [ 39.,  41.,  33.,

In [5]:
import numpy as np

medallas_csv_url = "./medallas.csv"
# remove the header
array = np.genfromtxt(medallas_csv_url,delimiter=',', filling_values=0,skip_header=1, dtype=int)
array

array([[  0,   1,   2,   3,   0],
       [  0,   2,   2,   4,   0],
       [ 17,   7,  22,  46,   0],
       [  1,   1,   5,   7,   0],
       [  0,   3,   4,   7,   0],
       [  2,   0,   0,   2,   0],
       [  0,   1,   0,   1,   0],
       [  1,   3,   3,   7,   0],
       [  3,   1,   3,   7,   0],
       [  1,   0,   0,   1,   0],
       [  0,   0,   1,   1,   0],
       [  7,   6,   8,  21,   0],
       [  3,   1,   2,   6,   0],
       [  0,   0,   1,   1,   0],
       [  7,   6,  11,  24,   0],
       [  2,   4,   6,  12,   0],
       [  0,   4,   1,   5,   0],
       [  3,   3,   2,   8,   0],
       [  0,   0,   1,   1,   0],
       [  7,   3,   5,  15,   0],
       [  4,   4,   3,  11,   0],
       [  3,   4,   4,  11,   0],
       [  0,   3,   2,   5,   0],
       [  2,   1,   0,   3,   0],
       [  1,   1,   4,   6,   0],
       [ 39,  41,  33, 113,   0],
       [  1,   0,   1,   2,   0],
       [  1,   1,   2,   4,   0],
       [  1,   0,   1,   2,   0],
       [  0,  

In [8]:
array_ejm = np.arange(1,7).reshape(2,3)
array_ejm_url = "./array_ejm.txt"
# fmt='%d' -> to generate number type int
np.savetxt(array_ejm_url, array_ejm, delimiter=',', fmt='%d')